{{- if .Values.networkpolicies.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "well-known.fullname" . }}-deny-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "well-known.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
	    {{- include "well-known.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "well-known.fullname" . }}-allow-ingress-webserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "well-known.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
	    {{- include "well-known.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "well-known.fullname" . }}-deny-egress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "well-known.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
	    {{- include "well-known.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "well-known.fullname" . }}-allow-egress-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "well-known.labels" . | nindent 4 }}
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
	    {{- include "well-known.selectorLabels" . | nindent 6 }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "well-known.fullname" . }}-allow-egress-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "well-known.labels" . | nindent 4 }}
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
	    {{- include "well-known.selectorLabels" . | nindent 6 }}
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkpolicies.kubeApiServerCIDR }}
    ports:
    - port: 443
      protocol: TCP
{{- end -}}